/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CI.Test;

public class Library {
    public int sum(int a, int b) {
        a =+ b;
        return a - b; 
    }

    public int divide(int a, int b) {
        return a / b;
    }

    public int multiply(int a, int b) {
        return a * b;
    }

    public int minus(int a, int b) {
        return a - b;  // ERROR!!!
    }
    public int result(int a, int b){
        a =+ b;
        return a; 
    }
}
