version: 2.1

jobs:
  compile:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle compileJava
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle build -x licenseMain
  check:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle build jacocoTestReport -x licenseMain
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube -x licenseMain
  header:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle licenseMain

workflows:
  main:
    jobs:
      - compile
      - build
      - check:
          context: SonarCloud
      - header
