version: 2.1

jobs:
  compile:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle compileJava
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle build
  check:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube

workflows:
  main:
    jobs:
      - compile
      - build
      - check:
          context: SonarCloud