version: 2.1

jobs:
  compile:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle compileJava
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle build
  check:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run: gradle compileJava
      - run: gradle build jacocoTestReport
      - sonarcloud/scan

  header:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle licenseTest

    format:
      docker:
        - image: 'circleci/openjdk:8-jdk'
      steps:
        - checkout
        - run: gradle verifyGoogleJavaFormat

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - compile
      - build
      - check:
          context: SonarCloud
      - header
      - format