version: 2.1

jobs:
  compile:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle compileJava
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run: gradle build

workflows:
  main:
    jobs:
      - compile
      - build