/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CI.Test;

import org.junit.Test;
import static org.junit.Assert.*;
import junit.framework.Assert;

public class LibraryTest {
    @Test
    public void testSum() {
        Library classUnderTest = new Library();
        int result = classUnderTest.sum(2, 2);
        if (result != 4) {
            Assert.fail();
        }
    }

    @Test
    public void testMinus() {
        Library classUnderTest = new Library();
        Assert.assertEquals(0, classUnderTest.minus(2, 1));
    }

    @Test
    public void testDivide() {
        Library classUnderTest = new Library();
        Assert.assertEquals(2, classUnderTest.divide(6, 3));
    }

    @Test(expected = ArithmeticException.class)
    public void testDivideWillThrowExceptionWhenDivideOnZero() {
        Library classUnderTest = new Library();
        classUnderTest.divide(6, 0);
    }

}
